#name: TextMatch Service CI

env:
  WORKING_DIRECTORY: TextMatch

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      ## configure GCP
      #- name: install the gcloud cli
      #  uses: google-github-actions/setup-gcloud@v0
      #  with:
      #    project_id: ${{ secrets.GOOGLE_PROJECT }}
      #    service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      #    export_default_credentials: true

      #- name: build, tag, and push the image to GCP
      #  working-directory: ./TextMatch
      #  id: build-api-image
      #  env:
      #    GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      #  run: |
      #    gcloud auth configure-docker us-central1-docker.pkg.dev
      #    docker build -t image/path .
      #    docker push image/path
