#name: TextMatch Service CI

env:
  WORKING_DIRECTORY: TextMatch

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      ## configure GCP
      #- name: install the gcloud cli
      #  uses: google-github-actions/setup-gcloud@v0
      #  with:
      #    project_id: ${{ secrets.GOOGLE_PROJECT }}
      #    service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      #    export_default_credentials: true

      #- name: build, tag, and push the image to GCP
      #  working-directory: ./TextMatch
      #  id: build-api-image
      #  env:
      #    GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      #  run: |
      #    gcloud auth configure-docker us-central1-docker.pkg.dev
      #    docker build -t image/path .
      #    docker push image/path
